const pages = [
{t:'The AKHARA Doctrine',type:'editorial',c:[`AKHARA is not built to feel like a generic agency. It is built to feel like a private strategic house: precise, quiet, premium, systems-driven, and deliberate.`,`We do not chase attention. We create gravity.`,`Nothing generic. Nothing cheap. Nothing accidental.`,`Every touchpoint must feel intentional.`,`The brand should feel like access to a higher standard.`]},
{t:'The Business Model',type:'split',lead:'AKHARA sells premium AI website + lead-system builds for high-ticket local businesses and premium operators.',quote:'“We build premium mobile-ready websites with WhatsApp lead capture, booking/contact flows, and AI-assisted follow-up systems for businesses that want to look premium and convert more enquiries.”',bul:['What the client thinks they need: a website','What they actually need: a better conversion system','What AKHARA sells: presentation, trust, lead capture, follow-up, and sales infrastructure']},
{t:'What AKHARA Offers',type:'cards',cards:['Premium Landing Pages','Offer Positioning','Lead Capture Systems','AI-Assisted Follow-Up','Sales Assets','Monthly Optimization']},
{t:'The AKHARA Offer Ladder',type:'ladder',tiers:[['Starter Build','R3,000 – R8,000'],['Authority Build','R8,000 – R18,000'],['AKHARA Signature System','R18,000 – R40,000+'],['Monthly Optimization Retainer','R3,000 – R15,000/month']]},
{t:'Who AKHARA Should Serve',type:'columns',left:['Car detailers','PPF/wrap shops','Luxury service businesses','Premium barbers','Real estate agents','Consultants','Coaches'],right:['They sell a service worth enough to justify premium presentation','Weak website/Instagram/WhatsApp enquiry process','They already get some enquiries','They understand missed leads cost money','They want to look better than competitors'],avoid:['Cheap clients only wanting lowest price','No value on presentation','No offer clarity','Expect guaranteed revenue without collaboration']},
{t:'Do Not Sell Websites. Sell Revenue Infrastructure.',type:'editorial',c:['Generic web designers sell pages. AKHARA sells a premium front-end business system.','“Your website should not just exist. It should convert.”','“We turn your online presence into a premium enquiry system.”','“You do not need another pretty page. You need a system that captures attention, builds trust, and directs people to act.”']},
{t:'The AKHARA Sales Flow',type:'flow',steps:['Find weak online presence','Audit website/social/WhatsApp flow','Send personalized message','Offer free mini-audit','Diagnose lead leakage','Present the system','Close setup fee','Upsell retainer after delivery']},
{t:'First Client Outreach',type:'scripts'},
{t:'The Delivery Blueprint',type:'flow',steps:['Intake','Positioning','Build','Lead Flow','Handoff','Retainer Path']},
{t:'Design Standards',type:'editorial',c:['Never overcrowd a page','Never let text overlap images or boxes','Use large spacing and fewer stronger words','Use black foundation, gold accent, white clarity','Use 3D visuals for impact, 2D logo for official identity','Every page should feel like a premium private document']},
{t:'How AKHARA Should Sound',type:'columns',left:['Confident','Strategic','Minimal','Premium','Direct','Controlled','High-standard'],right:['Avoid hype bro language','Avoid cheap urgency','Avoid generic agency claims','Avoid overpromising','Avoid desperate sales wording','Avoid guaranteed results language'],avoid:['premium','infrastructure','conversion','system','clarity','authority','positioning','scale','trust','high-ticket','private','strategic']},
{t:'How To Turn Builds Into Monthly Income',type:'editorial',c:['The first sale is the build. The long-term money is improvement.','Retainers: monthly updates, campaigns, lead tracking reports, script improvements, proposal updates, and conversion reviews.','“Your website and lead system should improve every month, not sit there collecting dust.”']},
{t:'How AKHARA Scales',type:'flow',steps:['Sell 1–3 starter builds manually','Turn delivery into templates and checklists','Create niche-specific packages','Build before/after case studies','Raise pricing and push retainers','Hire or automate repetitive tasks','Create internal operating system','Become known for premium AI website + lead-system builds']},
{t:'The AKHARA Standard',type:'editorial',c:['If it looks generic, rebuild it.','If the client cannot understand the offer in 5 seconds, clarify it.','If the CTA is weak, the system leaks money.','If the page does not feel premium on mobile, it is not done.','If layout feels cramped, it is not luxury.','If a serious operator would not respect it, it is not AKHARA.']},
{t:'Build It To A Level They Can Feel',type:'closing'}
];
const doc = document.querySelector('.document');
for (const p of pages){const s=document.createElement('section');s.className='page';s.innerHTML=`<header class='top'><img src='assets/akhara-2d-lockup.svg' class='logo'><img src='assets/akhara-geometric-logo.svg' class='seal'></header><h2>${p.t}</h2><div class='body'></div><footer>AKHARA</footer>`;const b=s.querySelector('.body');
if(p.type==='editorial') b.innerHTML=p.c.map(x=>`<p>${x}</p>`).join('');
if(p.type==='split') b.innerHTML=`<p>${p.lead}</p><blockquote>${p.quote}</blockquote><ul>${p.bul.map(x=>`<li>${x}</li>`).join('')}</ul>`;
if(p.type==='cards') b.innerHTML=`<div class='grid'>${p.cards.map(x=>`<article>${x}</article>`).join('')}</div>`;
if(p.type==='ladder') b.innerHTML=`<div class='ladder'>${p.tiers.map((x,i)=>`<article><span>Tier ${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div>`;
if(p.type==='columns') b.innerHTML=`<div class='cols'><ul>${p.left.map(x=>`<li>${x}</li>`).join('')}</ul><ul>${p.right.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class='avoid'><strong>${p.t.includes('Sound')?'Preferred language':'Avoid'}:</strong> ${p.avoid.join(' · ')}</div>`;
if(p.type==='flow') b.innerHTML=`<ol class='flow'>${p.steps.map(x=>`<li>${x}</li>`).join('')}</ol>`;
if(p.type==='scripts') b.innerHTML=`<article class='script'>“Hey [Name], I came across [Business]... Want me to send it?”</article><article class='script'>“Hey [Name], quick one — ... Want me to show you 2–3 quick improvements?”</article><article class='script'>“Hey [Name], your service looks premium... open to a quick audit?”</article>`;
if(p.type==='closing') b.innerHTML=`<img src='assets/akhara-3d-mark.svg' class='hero3d small'><p>AKHARA is not just a design business. It is a premium systems brand.</p><blockquote>“Premium is not decoration. Premium is control.”</blockquote><p class='tags'>AKHARA — Strategy • Systems • Scale</p>`;
doc.appendChild(s);}
